ess-uofc/ess-schulichhub

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
Tis just a one-line edit folks <3
=> Patch | Fixed GitHub Actions

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
Moved linter check before test deploy to save GitHub action time. Removed linter check from auto-deploy off main
=> Fix linter GitHub actions

package.json, src/App.tsx, src/components/HomePostView.tsx, src/components/PostContainer.css, src/components/PostContainer.tsx, src/pages/Home.css, src/pages/Home.tsx, yarn.lock
added a homepage. and posts about ratik and robert.
added lint command
=> Beginning of homepage

README.md
Very minor spacing issue fix on the README
=> Fix badge spacing issues

package.json, src/components/ExploreContainer.tsx, src/pages/Landing.scss, src/pages/Landing.tsx, yarn.lock
we were gonna put a version but we didnt know what it was...
=> Added base for landing page

src/components/PostContainer.scss, src/components/PostContainer.tsx, src/pages/Home.scss, src/pages/Home.tsx
Removed HTML tags and unnecessary SCSS code
=> removed remaining HTML tags

package.json, src/app/store.tsx, src/features/counter/Counter.scss, src/features/counter/Counter.tsx, src/features/counter/counterSlice.tsx, src/index.tsx, yarn.lock
- Added redux support
- Created Counter demo for redux applications
- Connected counter store to main app
*Please rebase onto main then merge after #35*
=> Add Redux functionality

src/App.tsx, src/components/CommentCompose.scss, src/components/CommentCompose.tsx, src/components/PostComments.scss, src/components/PostComments.tsx, src/pages/Post.scss, src/pages/Post.tsx
Added a skeleton for a single post view.
=> Added Single Post View

src/App.tsx, src/app/routing.tsx, src/pages/Login.tsx
/register and /emailregister were rerouting to /login.
Cleaned up and created a new function called redirectAfterAuthEvent
=> Applied fix for /register and other auth routes redirecting to /login

src/pages/Login.scss
Added a minimum width to inputs and buttons.
=> Fixed the login page scale on moblie

src/components/RegisterFormComp.tsx, src/components/RegisterLanding.scss, src/components/RegisterLandingComp.tsx, src/pages/RegisterForm.tsx, src/pages/RegisterLanding.tsx, src/pages/RegisterMain.scss
Fixed the scale of the register page to better resemble the rest of the site
Added the missing navbar to the page
=> Unified the Register page and fixed the navbar

src/Models/Comment.ts
Created a basic comment class based on the UML diagram for handling comments.
Changelog:
- Created comment files (src/Models/Comment.ts)
=> Comment Class

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, .github/workflows/version-bump.yml, package.json
This time on PR open it should do it
=> Test auto bump try #5

src/components/RegisterFormComp.tsx
Changelog:
- ../components/RegisterFormComp.tsx
- Added first and last name states and added new input for last name.
- Fixed user class static method call
=> Fixed Registration not working issue

src/Models/DocTypes.ts, src/Models/Post.ts, src/Models/User.ts, src/Models/firebase.ts, src/Models/firestore.ts, src/components/HomePostView.tsx, src/components/PostContainer.tsx, src/components/SingleComment.tsx, src/components/WritePost.tsx, src/pages/PostView.tsx
Changelog:
- HomePostView.tsx --> created firestore snapshot listener
-
=> Feature/live updates/lemohammed

src/components/LandingRegisterPrompt.tsx, src/components/RegisterLandingComp.tsx, src/pages/Login.tsx
The redirecting to the register page now comes with an animation.
Changelog:
•Changed the routing to the register page from the login page (src/pages/Login.tsx)
•Changed the routing to the register page from the landing page (src/components/LandingRegisterPrompt.tsx)
=> Fixed register page routing bug

src/components/LandingInfo.scss, src/components/LandingInfo.tsx
Changelog:
•Made the buttons stay the same width for mobile
(src/components/LandingInfo.scss)
•Corrected the format of the page so that when you shrink the size of the screen the paragraphs and their headers are in order (src/components/LandingInfo.tsx)
=> Fixed squished button bug on landing page for mobile

.github/workflows/firebase-hosting-merge.yml
Enabled auto-versioning on push to main
=> Enable push to protected branch

.github/labeler.yml, .github/workflows/automerge.yml, .github/workflows/labeler.yml, src/theme/variables.scss
This PR adds functionality to automatically merge PRs on status check passes and required number of reviews. Furthermore, labels will now be automatically added to PRs depending on what files have changed.
Changelog:
- Created `workflows/automerge.yml`
- Created `labeler.yml` and `workflows/labeler.yml`
=> feat: Autolabel and Automerge

src/App.tsx, src/Models/DocTypes.ts, src/components/CommentCompose.tsx, src/components/HomePostView.tsx, src/components/PostContainer.tsx, src/components/PrivateRoute.tsx, src/components/WritePost.tsx, src/pages/PostView.tsx
Changelog:
- fixed infinite loop useEffect bug causing excessive firebase reads
- Added selector component to HomePageView component to filter posts displayed by category
- Added Routing to PostView in PostContainer and App.tsx
- Loaded post content and displayed skeleton text in PostView accordingly
- Unsubscribed from firebase snapshot and auth state listeners after effect hook invocation
=> Added Post Routing to /potst/:id and added post filtering

.github/labeler.yml, .github/workflows/firebase-hosting-pull-request.yml, src/App.tsx, src/components/HomePostView.scss, src/components/RegisterFormComp.tsx, src/components/RegisterLanding.scss, src/components/RegisterLandingComp.tsx, src/components/TitleBar.tsx, src/components/WritePost.tsx, src/pages/Home.tsx, src/pages/Landing.scss, src/pages/Landing.tsx, src/pages/Login.tsx, src/pages/PostView.tsx, src/pages/RegisterForm.tsx, src/pages/RegisterLanding.tsx, src/pages/RegisterMain.scss, src/pages/WritePost.tsx
Changed the titlebar to be rendered in component in `app.tsx` opposed to each page, and added an profile icon to the titlebar.
Changelog:
- Created `Titlebar.tsx` to render the titlebar
- Added a `IonChip` and `IonAvatar` for a profile button.
=> feat: Moved TitleBar to a component and added a profile button.

src/App.tsx, src/app/routing.tsx, src/app/toast.ts, src/components/HomePostView.tsx, src/components/Loading.tsx, src/components/PostContainer.tsx, src/components/PostContainerSkeleton.tsx, src/components/PrivateRoute.tsx, src/components/RegisterFormComp.tsx, src/pages/Login.scss, src/pages/Login.tsx, src/pages/PostView.tsx
Changed alerts to toasts
Changed private routing to return Login component instead of login route
Removed old routing function to use History react hook (better since the page does not refresh)
=> fix: Routing Bug

.dockerignore, Dockerfile, README.md, docker-compose.yml
Containerized development environment using Docker and docker-compose. Instructions have also been updated to match new development flow using Docker 🐳 .
Chanelog:
- Created Dockerfile, docker-compose.yml, and .dockerignore and added containerization functionality
- Updated README to include new development instructions using docker
=> feat: Added Docker support 🐳 

.github/labeler.yml, Dockerfile, README.md, package.json
Closes #100.
Changelog:
- Added `yarn` command before starting React app in docker container using `docker-compose up`
- Added Docker file recognition to PR labeler
- Added Docker scripts for yarn and updated README
=> fix: Dockerfile now runs yarn before starting

package.json, src/components/PostContainer.scss, src/components/PostContainer.tsx, src/pages/PostView.scss, yarn.lock
ChangeLog:
- Corrected line break in `PostContainer.tsx` and added a max height
- Added vertical scrolling bar in `PostView.scss`
=> fixed line break [issue 93] and added scrolling bar for PostView

src/Models/Auth.ts, src/Models/PrimaryUser.ts, src/components/CommentCompose.tsx, src/components/HomePostView.tsx, src/pages/Home.tsx, src/pages/Login.tsx, src/pages/PostView.tsx
Changelog:
Pages: 
- disabled Write a post button
- fixed text field is editable issue
- fixed user passed as prop to comment compose in post view
Models:
- Added isEmailVerified method
Components:
- Disabled submit and write post view buttons accordingly
=> Feat: Added check for email verified before letting user write post or comment

src/Models/Comment.ts, src/Models/DocTypes.ts, src/Models/Post.ts, src/Models/firebase.ts, src/components/CommentCompose.tsx, src/components/PostContainer.tsx, src/components/WritePost.tsx, src/pages/PostView.tsx
ChangeLog:
- ./Models/Comment.tsx
- ./Models/Post.tsx
- ./Models/firebase.tsx
- ./components/CommentCompose.tsx
- ./components/WritePost.tsx
- ./components/PostView.tsx
Fixed Post Comments Sorting bug
=> Feat: Added post and comment aggregation definitions

src/App.tsx, src/pages/Landing.scss, src/pages/ProfileView.scss, src/pages/ProfileView.tsx, yarn.lock
Added the post view with spots to hook in auth and data
=> feat: Added basic post view

.github/workflows/firebase-hosting-release.yml
Changelog:
- Channel ID for releases set to live
=> fix: Release channel ID
